#pragma once

#include <string>

static const std::string mnemonics[256] = {
    "nop",
    "ld %bc, #i16",
    "ld *%bc, %a",
    "inc %bc",
    "inc %b",
    "dec %b",
    "ld %b, #i8",
    "rlca",
    "ld *#i16,sp",
    "add %hl, %bc",
    "ld %a, *%bc",
    "dec %bc",
    "inc %c",
    "dec %c",
    "ld %c, #i8",
    "rrca",

    "stop",
    "ld %de, #i16",
    "ld *%de, %a",
    "inc %de",
    "inc %d",
    "dec %d",
    "ld %d, #i8",
    "rla",
    "jr #i8",
    "add %hl, %de",
    "ld %a, *%de",
    "dec %de",
    "inc %e",
    "dec %e",
    "ld %e, #i8",
    "rra",

    "jrnz #i8",
    "ld %hl, #i16",
    "ld *%hl+, %a",
    "inc %hl",
    "inc %h",
    "dec %h",
    "ld %h, #i8",
    "daa",
    "jrz #i8",
    "add %hl, %hl",
    "ld %a, *%hl+",
    "dec %hl",
    "inc %l",
    "dec %l",
    "ld %l, #i8",
    "cpl",

    "jr nc, #i8",
    "ld sp, #i16",
    "ld *%hl-, %a",
    "inc sp",
    "inc *%hl",
    "dec *%hl",
    "ld *%hl, #i8",
    "scf",
    "jrc #i8",
    "add %hl,sp",
    "ld %a, *%hl-",
    "dec sp",
    "inc %a",
    "dec %a",
    "lda, #i8",
    "ccf",

    "ld %b, %b",
    "ld %b, %c",
    "ld %b, %d",
    "ld %b, %e",
    "ld %b, %h",
    "ld %b, %l",
    "ld %b, *%hl",
    "ld %b, %a",
    "ld %c, %b",
    "ld %c, %c",
    "ld %c, %d",
    "ld %c, %e",
    "ld %c, %h",
    "ld %c, %l",
    "ld %c, *%hl",
    "ld %c, %a",

    "ld %d, %b",
    "ld %d, %c",
    "ld %d, %d",
    "ld %d, %e",
    "ld %d, %h",
    "ld %d, %l",
    "ld %d, *%hl",
    "ld %d, %a",
    "ld %e, %b",
    "ld %e, %c",
    "ld %e, %d",
    "ld %e, %e",
    "ld %e, %h",
    "ld %e, %l",
    "ld %e, *%hl",
    "ld %e, %a",

    "ld %h, %b",
    "ld %h, %c",
    "ld %h, %d",
    "ld %h, %e",
    "ld %h, %h",
    "ld %h, %l",
    "ld %h, *%hl",
    "ld %h, %a",
    "ld %l, %b",
    "ld %l, %c",
    "ld %l, %d",
    "ld %l, %e",
    "ld %l, %h",
    "ld %l, %l",
    "ld %l, *%hl",
    "ld %l, %a",

    "ld *%hl, %b",
    "ld *%hl, %c",
    "ld *%hl, %d",
    "ld *%hl, %e",
    "ld *%hl, %h",
    "ld *%hl, %l",
    "halt",
    "ld *%hl, %a",
    "ld %a, %b",
    "ld %a, %c",
    "ld %a, %d",
    "ld %a, %e",
    "ld %a, %h",
    "ld %a, %l",
    "ld %a, *%hl",
    "ld %a, %a",

    "add %a, %b",
    "add %a, %c",
    "add %a, %d",
    "add %a, %e",
    "add %a, %h",
    "add %a, %l",
    "add %a, *%hl",
    "add %a, %a",
    "adc %a, %b",
    "adc %a, %c",
    "adc %a, %d",
    "adc %a, %e",
    "adc %a, %h",
    "adc %a, %l",
    "adc %a, *%hl",
    "adc %a, %a",

    "sub %b",
    "sub %c",
    "sub %d",
    "sub %e",
    "sub %h",
    "sub %l",
    "sub *%hl",
    "sub %a",
    "sbc %a, %b",
    "sbc %a, %c",
    "sbc %a, %d",
    "sbc %a, %e",
    "sbc %a, %h",
    "sbc %a, %l",
    "sbc %a, *%hl",
    "sbc %a, %a",

    "and %b",
    "and %c",
    "and %d",
    "and %e",
    "and %h",
    "and %l",
    "and *%hl",
    "and %a",
    "xor %b",
    "xor %c",
    "xor %d",
    "xor %e",
    "xor %h",
    "xor %l",
    "xor *%hl",
    "xor %a",

    "or %b",
    "or %c",
    "or %d",
    "or %e",
    "or %h",
    "or %l",
    "or *%hl",
    "or %a",
    "cp %b",
    "cp %c",
    "cp %d",
    "cp %e",
    "cp %h",
    "cp %l",
    "cp *%hl",
    "cp %a",

    "retnz",
    "pop %bc",
    "jpnz #i16",
    "jp #i16",
    "callnz #i16",
    "push %bc",
    "add %a, #i8",
    "rst",
    "retz",
    "ret",
    "jpz #i16",
    "cb opcode",
    "callz #i16",
    "call #i16",
    "adc %a, #i8",
    "rst #0x08",

    "ret nc",
    "pop %de",
    "jp nc, #i16",
    "unused opcode",
    "call nc, #i16",
    "push %de",
    "sub #i8",
    "rst #0x10",
    "ret %c",
    "reti",
    "jpc #i16",
    "unused opcode",
    "callc #i16",
    "unused opcode",
    "sbc %a, #i8",
    "rst #0x18",

    "ld *#0xff00+#i8, %a",
    "pop %hl",
    "ld *#0xff00+%c, %a",
    "unused opcode",
    "unused opcode",
    "push %hl",
    "and #i8",
    "rst #0x20",
    "add sp, #i8",
    "jp *%hl",
    "ld *#i16, %a",
    "unused opcode",
    "unused opcode",
    "unused opcode",
    "xor #i8",
    "rst #0x28",

    "ld %a, *#0xff00+#i8",
    "pop %af",
    "ld %a, *#0xff00+%c",
    "di",
    "unused opcode",
    "push %af",
    "or #i8",
    "rst #0x30",
    "ld %hl,sp",
    "ld sp, %hl",
    "ld %a, *#i16",
    "ei",
    "unused opcode",
    "unused opcode",
    "cp #i8",
    "rst #0x38"
};